# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caprofile',
            name='collegeAddress',
        ),
        migrations.AddField(
            model_name='caprofile',
            name='whatsappNumber',
            field=models.BigIntegerField(default=1234),
            preserve_default=False,
        ),
    ]
