# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0002_auto_20160916_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyprofile',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KYusers.College'),
        ),
    ]
