# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0005_auto_20160918_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyprofile',
            name='referralCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
