# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-24 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0006_kyprofile_referralcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyprofile',
            old_name='mobile_number',
            new_name='mobileNumber',
        ),
    ]
