# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0007_auto_20160924_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, 'Sex'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kyprofile',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Year'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], null=True),
        ),
    ]
