# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0008_auto_20160927_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='whyChooseYou',
            field=models.TextField(blank=True, null=True),
        ),
    ]
