# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0010_auto_20160927_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='whatsappNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
