# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0011_auto_20160927_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyprofile',
            name='mobileNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
