# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 15:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0012_auto_20160927_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='caprofile',
            name='isChoosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='fblink',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
