# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0013_auto_20160927_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='caId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
