# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0014_auto_20160929_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgotPassKey', models.CharField(blank=True, max_length=250, null=True)),
                ('confirmationKey', models.CharField(blank=True, max_length=250, null=True)),
                ('kyprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KYusers.KYProfile')),
            ],
        ),
    ]
