# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0015_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='regNum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
