# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-12 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0016_auto_20161003_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='caprofile',
            name='regs',
            field=models.ManyToManyField(blank=True, null=True, related_name='regs', to='KYusers.KYProfile'),
        ),
    ]
