# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0017_caprofile_regs'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mard_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='regs',
            field=models.ManyToManyField(blank=True, related_name='regs', to='KYusers.KYProfile'),
        ),
    ]
