# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0018_auto_20161028_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mard_read',
            new_name='mark_read',
        ),
    ]
