# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0019_auto_20161028_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='regCount',
            field=models.IntegerField(default=0),
        ),
    ]
