# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0021_kyprofile_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyprofile',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
