# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0022_kyprofile_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AddField(
            model_name='message',
            name='mobileNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
