# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KYusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50)),
                ('maxMembers', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentEvent',
            fields=[
                ('parentEventId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('members', models.ManyToManyField(related_name='members', to='KYusers.KYProfile')),
                ('teamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamLeader', to='KYusers.KYProfile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='parentEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ParentEvent'),
        ),
    ]
