# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KYusers', '0020_college_regcount'),
        ('events', '0002_event_eventdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contingent',
            fields=[
                ('contingentId', models.AutoField(primary_key=True, serialize=False)),
                ('contingentLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='KYusers.KYProfile')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KYusers.KYProfile')),
            ],
        ),
    ]
