# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_contingent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contingent',
            name='contingentLeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_leader', to='KYusers.KYProfile'),
        ),
        migrations.AlterField(
            model_name='contingent',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='con_members', to='KYusers.KYProfile'),
        ),
    ]
