# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20161110_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='minMembers',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
