# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-28 17:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponserTag', models.CharField(max_length=250)),
                ('sponserName', models.CharField(max_length=250)),
                ('photo', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
